### ISSUE TITLE
显卡兼容问题

### ISSUE THREAD

**Issue by PinkOrangeee** [softwarePupil/ImgProcess#4]
UserWarning: 
NVIDIA GeForce RTX 3050 Laptop GPU with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_61 sm_70 sm_75 compute_37.
If you want to use the NVIDIA GeForce RTX 3050 Laptop GPU GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/
请问我在训练模型时遇到这个问题，是代表我无法使用GPU吗？
我在尝试了将CUDA版本更新为1.11，pytorch更新为1.8.0后没有以上不兼容问题，但会有其他的报错，请问这种情况该如何处理呢？

**Comment by softwarePupil** [comment]
请你将其他报错展示一下，如果显卡为30系，那么只能安装CUDA11以上的版本，这同时对pytorch有了限制。不过我认为代码应该可以适应pytorch1.8.0，还是请你将报错展示一下

**Comment by PinkOrangeee** [comment]
谢谢老师的提醒，我以为报错问题会是跟pytorch版本有关，现已解决
